USE [master]
GO
/****** Object:  Database [yemektarifleriDB]    Script Date: 30.12.2023 18:12:26 ******/
CREATE DATABASE [yemektarifleriDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'yemektarifleriDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\yemektarifleriDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'yemektarifleriDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\yemektarifleriDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [yemektarifleriDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [yemektarifleriDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [yemektarifleriDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [yemektarifleriDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [yemektarifleriDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [yemektarifleriDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [yemektarifleriDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET RECOVERY FULL 
GO
ALTER DATABASE [yemektarifleriDB] SET  MULTI_USER 
GO
ALTER DATABASE [yemektarifleriDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [yemektarifleriDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [yemektarifleriDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [yemektarifleriDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [yemektarifleriDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [yemektarifleriDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'yemektarifleriDB', N'ON'
GO
ALTER DATABASE [yemektarifleriDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [yemektarifleriDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [yemektarifleriDB]
GO
/****** Object:  Table [dbo].[Kategoriler]    Script Date: 30.12.2023 18:12:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kategoriler](
	[kategoriID] [int] IDENTITY(1,1) NOT NULL,
	[kategoriadi] [nvarchar](200) NULL,
	[aktif] [bit] NULL,
	[silindi] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[kategoriID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Kullanicilar]    Script Date: 30.12.2023 18:12:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kullanicilar](
	[kullaniciID] [int] IDENTITY(1,1) NOT NULL,
	[adi] [nvarchar](200) NULL,
	[soyadi] [nvarchar](200) NULL,
	[eposta] [nvarchar](200) NULL,
	[telefon] [nvarchar](15) NULL,
	[parola] [nvarchar](25) NULL,
	[yetki] [bit] NULL,
	[aktif] [bit] NULL,
	[silindi] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[kullaniciID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Menuler]    Script Date: 30.12.2023 18:12:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Menuler](
	[menuID] [int] IDENTITY(1,1) NOT NULL,
	[baslik] [nvarchar](250) NULL,
	[url] [nvarchar](255) NULL,
	[sira] [tinyint] NULL,
	[ustID] [int] NULL,
	[aktif] [bit] NULL,
	[silindi] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[menuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sayfalar]    Script Date: 30.12.2023 18:12:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sayfalar](
	[sayfaID] [int] IDENTITY(1,1) NOT NULL,
	[baslik] [nvarchar](250) NULL,
	[icerik] [ntext] NULL,
	[aktif] [bit] NULL,
	[silindi] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[sayfaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[YemekTarifleri]    Script Date: 30.12.2023 18:12:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[YemekTarifleri](
	[tarifID] [int] IDENTITY(1,1) NOT NULL,
	[yemekadi] [nvarchar](250) NULL,
	[tarif] [ntext] NULL,
	[sira] [tinyint] NULL,
	[kategoriID] [int] NULL,
	[eklemetarihi] [datetime] NULL,
	[aktif] [bit] NULL,
	[silindi] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[tarifID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Yorumlar]    Script Date: 30.12.2023 18:12:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Yorumlar](
	[yorumID] [int] IDENTITY(1,1) NOT NULL,
	[yorum] [nvarchar](500) NULL,
	[eklemetarihi] [datetime] NULL,
	[tarifID] [int] NULL,
	[uyeID] [int] NULL,
	[aktif] [bit] NULL,
	[silindi] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[yorumID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[YemekTarifleri]  WITH CHECK ADD FOREIGN KEY([kategoriID])
REFERENCES [dbo].[Kategoriler] ([kategoriID])
GO
ALTER TABLE [dbo].[Yorumlar]  WITH CHECK ADD FOREIGN KEY([tarifID])
REFERENCES [dbo].[YemekTarifleri] ([tarifID])
GO
ALTER TABLE [dbo].[Yorumlar]  WITH CHECK ADD FOREIGN KEY([uyeID])
REFERENCES [dbo].[Kullanicilar] ([kullaniciID])
GO
USE [master]
GO
ALTER DATABASE [yemektarifleriDB] SET  READ_WRITE 
GO
